--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06.04.2020 11:24:54
-- Server version: 5.5.5-10.3.13-MariaDB-log
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE schedule;

--
-- Drop table `schedule`
--
DROP TABLE IF EXISTS schedule;

--
-- Drop table `classroom`
--
DROP TABLE IF EXISTS classroom;

--
-- Drop table `day`
--
DROP TABLE IF EXISTS day;

--
-- Drop table `lesson_num`
--
DROP TABLE IF EXISTS lesson_num;

--
-- Drop table `lesson_plan`
--
DROP TABLE IF EXISTS lesson_plan;

--
-- Drop table `student`
--
DROP TABLE IF EXISTS student;

--
-- Drop table `gruppa`
--
DROP TABLE IF EXISTS gruppa;

--
-- Drop table `special`
--
DROP TABLE IF EXISTS special;

--
-- Drop table `subject`
--
DROP TABLE IF EXISTS subject;

--
-- Drop table `teacher`
--
DROP TABLE IF EXISTS teacher;

--
-- Drop table `otdel`
--
DROP TABLE IF EXISTS otdel;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop table `gender`
--
DROP TABLE IF EXISTS gender;

--
-- Drop table `role`
--
DROP TABLE IF EXISTS role;

--
-- Set default database
--
USE schedule;

--
-- Create table `role`
--
CREATE TABLE role (
  role_id tinyint(4) NOT NULL AUTO_INCREMENT,
  sys_name varchar(20) NOT NULL,
  name varchar(20) NOT NULL,
  active tinyint(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (role_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `gender`
--
CREATE TABLE gender (
  gender_id tinyint(4) NOT NULL AUTO_INCREMENT,
  name varchar(10) NOT NULL,
  PRIMARY KEY (gender_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `user`
--
CREATE TABLE user (
  user_id bigint(20) NOT NULL AUTO_INCREMENT,
  lastname varchar(50) NOT NULL,
  firstname varchar(50) DEFAULT NULL,
  patronymic varchar(50) DEFAULT NULL,
  login varchar(50) DEFAULT NULL,
  pass varchar(255) DEFAULT NULL,
  gender_id tinyint(4) NOT NULL,
  birthday date DEFAULT NULL,
  role_id tinyint(4) NOT NULL,
  active tinyint(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE user
ADD CONSTRAINT FK_user_gender_gender_id FOREIGN KEY (gender_id)
REFERENCES gender (gender_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE user
ADD CONSTRAINT FK_user_role_role_id FOREIGN KEY (role_id)
REFERENCES role (role_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `otdel`
--
CREATE TABLE otdel (
  otdel_id smallint(6) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  active tinyint(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (otdel_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `teacher`
--
CREATE TABLE teacher (
  user_id bigint(20) NOT NULL,
  otdel_id smallint(6) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE teacher
ADD CONSTRAINT FK_teacher_otdel_otdel_id FOREIGN KEY (otdel_id)
REFERENCES otdel (otdel_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE teacher
ADD CONSTRAINT FK_teacher_user_user_id FOREIGN KEY (user_id)
REFERENCES user (user_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `subject`
--
CREATE TABLE subject (
  subject_id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  otdel_id smallint(6) NOT NULL,
  hours smallint(6) NOT NULL,
  active tinyint(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (subject_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE subject
ADD CONSTRAINT FK_subject_otdel_otdel_id FOREIGN KEY (otdel_id)
REFERENCES otdel (otdel_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `special`
--
CREATE TABLE special (
  special_id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(250) NOT NULL,
  otdel_id smallint(6) NOT NULL,
  active tinyint(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (special_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE special
ADD CONSTRAINT FK_special_otdel_otdel_id FOREIGN KEY (otdel_id)
REFERENCES otdel (otdel_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `gruppa`
--
CREATE TABLE gruppa (
  gruppa_id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(10) NOT NULL,
  special_id int(11) NOT NULL,
  date_begin date NOT NULL,
  date_end date DEFAULT NULL,
  PRIMARY KEY (gruppa_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE gruppa
ADD CONSTRAINT FK_gruppa_special_special_id FOREIGN KEY (special_id)
REFERENCES special (special_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `student`
--
CREATE TABLE student (
  user_id bigint(20) NOT NULL,
  gruppa_id int(11) NOT NULL,
  num_zach varchar(10) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE student
ADD CONSTRAINT FK_student_gruppa_gruppa_id FOREIGN KEY (gruppa_id)
REFERENCES gruppa (gruppa_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE student
ADD CONSTRAINT FK_student_user_user_id FOREIGN KEY (user_id)
REFERENCES user (user_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `lesson_plan`
--
CREATE TABLE lesson_plan (
  lesson_plan_id int(11) NOT NULL AUTO_INCREMENT,
  gruppa_id int(11) NOT NULL,
  subject_id int(11) NOT NULL,
  user_id bigint(20) NOT NULL,
  PRIMARY KEY (lesson_plan_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE lesson_plan
ADD CONSTRAINT FK_lesson_plan_gruppa_gruppa_id FOREIGN KEY (gruppa_id)
REFERENCES gruppa (gruppa_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE lesson_plan
ADD CONSTRAINT FK_lesson_plan_subject_subject_id FOREIGN KEY (subject_id)
REFERENCES subject (subject_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE lesson_plan
ADD CONSTRAINT FK_lesson_plan_teacher_user_id FOREIGN KEY (user_id)
REFERENCES teacher (user_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `lesson_num`
--
CREATE TABLE lesson_num (
  lesson_num_id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  time_lesson time NOT NULL,
  PRIMARY KEY (lesson_num_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `day`
--
CREATE TABLE day (
  day_id tinyint(4) NOT NULL AUTO_INCREMENT,
  name varchar(20) NOT NULL,
  PRIMARY KEY (day_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `classroom`
--
CREATE TABLE classroom (
  classroom_id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(20) NOT NULL,
  active tinyint(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (classroom_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `schedule`
--
CREATE TABLE schedule (
  schedule_id int(11) NOT NULL AUTO_INCREMENT,
  lesson_plan_id int(11) NOT NULL,
  day_id tinyint(4) NOT NULL,
  lesson_num_id int(11) NOT NULL,
  classroom_id int(11) NOT NULL,
  PRIMARY KEY (schedule_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE schedule
ADD CONSTRAINT FK_schedule_classroom_classroom_id FOREIGN KEY (classroom_id)
REFERENCES classroom (classroom_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE schedule
ADD CONSTRAINT FK_schedule_day_day_id FOREIGN KEY (day_id)
REFERENCES day (day_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE schedule
ADD CONSTRAINT FK_schedule_lesson_num_lesson_num_id FOREIGN KEY (lesson_num_id)
REFERENCES lesson_num (lesson_num_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE schedule
ADD CONSTRAINT FK_schedule_lesson_plan_lesson_plan_id FOREIGN KEY (lesson_plan_id)
REFERENCES lesson_plan (lesson_plan_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table role
--
INSERT INTO role VALUES
(1, 'admin', 'администратор', 1),
(2, 'manager', 'менеджер', 1),
(3, 'teacher', 'учитель', 1),
(4, 'student', 'студент', 1);

-- 
-- Dumping data for table gender
--
INSERT INTO gender VALUES
(1, 'Мужской'),
(2, 'Женский');

-- 
-- Dumping data for table user
--
-- Table schedule.user does not contain any data (it is empty)

-- 
-- Dumping data for table otdel
--
INSERT INTO otdel VALUES
(1, 'Программирование', 1),
(2, 'Общеобразовательные дисциплины', 1),
(3, 'Строительство', 1);

-- 
-- Dumping data for table special
--
INSERT INTO special VALUES
(1, 'Информационные системы', 1, 1),
(2, 'Нефтегазовое дело', 2, 1),
(3, 'Строительство и эксплуатация зданий и сооружений', 3, 1),
(4, 'Электроснабжение', 3, 1),
(5, 'ВТ и ПО', 1, 1);

-- 
-- Dumping data for table teacher
--
-- Table schedule.teacher does not contain any data (it is empty)

-- 
-- Dumping data for table subject
--
-- Table schedule.subject does not contain any data (it is empty)

-- 
-- Dumping data for table gruppa
--
-- Table schedule.gruppa does not contain any data (it is empty)

-- 
-- Dumping data for table lesson_plan
--
-- Table schedule.lesson_plan does not contain any data (it is empty)

-- 
-- Dumping data for table lesson_num
--
INSERT INTO lesson_num VALUES
(1, '1 пара', '08:30:00'),
(2, '2 пара', '10:10:00'),
(3, '3 пара', '12:20:00'),
(4, '4 пара', '14:00:00'),
(5, '5 пара', '15:40:00');

-- 
-- Dumping data for table day
--
INSERT INTO day VALUES
(1, 'Понедельник'),
(2, 'Вторник'),
(3, 'Среда'),
(4, 'Четверг'),
(5, 'Пятница'),
(6, 'Суббота'),
(7, '');

-- 
-- Dumping data for table classroom
--
-- Table schedule.classroom does not contain any data (it is empty)

-- 
-- Dumping data for table student
--
-- Table schedule.student does not contain any data (it is empty)

-- 
-- Dumping data for table schedule
--
-- Table schedule.schedule does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;